# Generated by Django 4.2.3 on 2023-08-03 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('polish', models.CharField(choices=[('W', 'Wax'), ('P', 'Polish'), ('S', 'Shine')], default='W', max_length=1)),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ring')),
            ],
        ),
    ]
