# Generated by Django 4.2.3 on 2023-08-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ring',
            name='owners',
            field=models.ManyToManyField(to='main_app.owner'),
        ),
    ]
